refactor(crypto-transaction): use RLP for serialization
ArkEcosystem/mainsail pull request #800
Opened 2024-12-12 13:46 UTC by sebastijankuzner

## Summary

Make transactions EVM compatible. 

## Checklist

- [x] Tests _(if necessary)_
- [x] Ready to be merged

2024-12-16 02:11 UTC, oXtxNt9U requested changes, later dismissed

2024-12-16 02:11 UTC, oXtxNt9U commented on packages/crypto-transaction/source/validation/schemas.ts
> +		r: { type: "string" }, // TODO: prefixed hex
limit length (64 or 65 with prefix)

2024-12-16 02:11 UTC, oXtxNt9U commented on packages/crypto-transaction/source/verifier.ts
> +		if (!v || !r || !s || !senderPublicKey) {
If `v` can be 0 then this also evaluates to false. Double check

2024-12-16 02:11 UTC, oXtxNt9U commented on packages/crypto-block/test/helpers/prepare-sandbox.ts
> +	const builder = context.sandbox.app.resolve(EvmCallBuilder);
Code below just for debugging? (if so, can be removed)

2024-12-16 02:11 UTC, oXtxNt9U commented on packages/crypto-block/source/factory.test.ts
> +	it.skip("#fromData - should create a block with transactions instance from an object", async (context) => {
All tests should be fixed instead of skipped (also remove `.only`)

2024-12-16 02:11 UTC, oXtxNt9U commented on packages/api-sync/source/service.ts
> +				// signature: data.signature,
We can concatenate the `r,s,v` components

2024-12-16 02:11 UTC, oXtxNt9U commented on packages/api-sync/source/restore.ts
> +						// signature: data.signature,
We can concatenate the `r,s,v` components

2024-12-16 09:19 UTC, sebastijankuzner commented on packages/crypto-transaction/source/verifier.ts
> +		if (!v || !r || !s || !senderPublicKey) {
I am using 27 & 28 values. 27 => false, 28 => true.

2024-12-18 05:06 UTC, oXtxNt9U commented
changing to draft to prevent accidental merge

2025-01-07 12:41 UTC, sebastijankuzner commented on packages/crypto-transaction/source/validation/schemas.ts
> +		r: { type: "string" }, // TODO: prefixed hex
Will prepare separate PR.

2025-01-07 12:47 UTC, sebastijankuzner commented on packages/api-sync/source/service.ts
> +				// signature: data.signature,
Prepare separate PR.

2025-01-07 12:47 UTC, sebastijankuzner commented on packages/api-sync/source/restore.ts
> +						// signature: data.signature,
Prepare separate PR.

2025-01-07 15:38 UTC, merged